# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'inter.ui'
#
# Created: Fri Apr 24 13:27:32 2015
#      by: PyQt4 UI code generator 4.9.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(871, 644)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.groupBox = QtGui.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(480, 15, 381, 301))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.lineEdit = QtGui.QLineEdit(self.groupBox)
        self.lineEdit.setGeometry(QtCore.QRect(10, 60, 331, 20))
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(10, 180, 81, 16))
        self.label.setObjectName(_fromUtf8("label"))
        self.lineEdit_2 = QtGui.QLineEdit(self.groupBox)
        self.lineEdit_2.setGeometry(QtCore.QRect(10, 200, 331, 41))
        self.lineEdit_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.lineEdit_2.setReadOnly(True)
        self.lineEdit_2.setObjectName(_fromUtf8("lineEdit_2"))
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(10, 250, 61, 16))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.progressBar = QtGui.QProgressBar(self.groupBox)
        self.progressBar.setGeometry(QtCore.QRect(6, 270, 371, 16))
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName(_fromUtf8("progressBar"))
        self.splitter = QtGui.QSplitter(self.groupBox)
        self.splitter.setGeometry(QtCore.QRect(10, 100, 171, 20))
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.label_11 = QtGui.QLabel(self.splitter)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.comboBox = QtGui.QComboBox(self.splitter)
        self.comboBox.setObjectName(_fromUtf8("comboBox"))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.pushButton_4 = QtGui.QPushButton(self.groupBox)
        self.pushButton_4.setGeometry(QtCore.QRect(110, 30, 104, 23))
        self.pushButton_4.setObjectName(_fromUtf8("pushButton_4"))
        self.pushButton = QtGui.QPushButton(self.groupBox)
        self.pushButton.setGeometry(QtCore.QRect(11, 30, 104, 23))
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.pushButton_2 = QtGui.QPushButton(self.groupBox)
        self.pushButton_2.setGeometry(QtCore.QRect(10, 140, 104, 23))
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.label_18 = QtGui.QLabel(self.groupBox)
        self.label_18.setGeometry(QtCore.QRect(198, 102, 51, 16))
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.comboBox_4 = QtGui.QComboBox(self.groupBox)
        self.comboBox_4.setGeometry(QtCore.QRect(248, 100, 43, 20))
        self.comboBox_4.setObjectName(_fromUtf8("comboBox_4"))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.comboBox_5 = QtGui.QComboBox(self.groupBox)
        self.comboBox_5.setGeometry(QtCore.QRect(298, 100, 43, 20))
        self.comboBox_5.setObjectName(_fromUtf8("comboBox_5"))
        self.comboBox_5.addItem(_fromUtf8(""))
        self.comboBox_5.addItem(_fromUtf8(""))
        self.comboBox_5.addItem(_fromUtf8(""))
        self.comboBox_5.addItem(_fromUtf8(""))
        self.comboBox_5.addItem(_fromUtf8(""))
        self.comboBox_5.addItem(_fromUtf8(""))
        self.comboBox_5.addItem(_fromUtf8(""))
        self.comboBox_5.addItem(_fromUtf8(""))
        self.comboBox_5.addItem(_fromUtf8(""))
        self.comboBox_5.addItem(_fromUtf8(""))
        self.comboBox_5.addItem(_fromUtf8(""))
        self.comboBox_5.addItem(_fromUtf8(""))
        self.radioButton = QtGui.QRadioButton(self.groupBox)
        self.radioButton.setGeometry(QtCore.QRect(140, 143, 82, 17))
        self.radioButton.setChecked(True)
        self.radioButton.setObjectName(_fromUtf8("radioButton"))
        self.radioButton_2 = QtGui.QRadioButton(self.groupBox)
        self.radioButton_2.setGeometry(QtCore.QRect(230, 143, 82, 17))
        self.radioButton_2.setObjectName(_fromUtf8("radioButton_2"))
        self.frame = QtGui.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(140, 129, 120, 241))
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 471, 381))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.widget = QtGui.QWidget()
        self.widget.setObjectName(_fromUtf8("widget"))
        self.label_4 = QtGui.QLabel(self.widget)
        self.label_4.setGeometry(QtCore.QRect(180, 600, 46, 20))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.mplwidget_3 = MatplotlibWidget(self.widget)
        self.mplwidget_3.setGeometry(QtCore.QRect(0, 0, 471, 361))
        self.mplwidget_3.setObjectName(_fromUtf8("mplwidget_3"))
        self.tabWidget.addTab(self.widget, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.mplwidget_2 = MatplotlibWidget(self.tab_2)
        self.mplwidget_2.setGeometry(QtCore.QRect(0, 0, 471, 361))
        self.mplwidget_2.setObjectName(_fromUtf8("mplwidget_2"))
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.groupBox_2 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(0, 380, 471, 231))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.label_3 = QtGui.QLabel(self.groupBox_2)
        self.label_3.setGeometry(QtCore.QRect(80, 30, 71, 20))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.lineEdit_3 = QtGui.QLineEdit(self.groupBox_2)
        self.lineEdit_3.setGeometry(QtCore.QRect(520, 30, 91, 20))
        self.lineEdit_3.setObjectName(_fromUtf8("lineEdit_3"))
        self.label_5 = QtGui.QLabel(self.groupBox_2)
        self.label_5.setGeometry(QtCore.QRect(280, 30, 46, 20))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.lineEdit_4 = QtGui.QLineEdit(self.groupBox_2)
        self.lineEdit_4.setEnabled(False)
        self.lineEdit_4.setGeometry(QtCore.QRect(320, 30, 41, 20))
        self.lineEdit_4.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_4.setObjectName(_fromUtf8("lineEdit_4"))
        self.lineEdit_5 = QtGui.QLineEdit(self.groupBox_2)
        self.lineEdit_5.setEnabled(False)
        self.lineEdit_5.setGeometry(QtCore.QRect(150, 60, 91, 20))
        self.lineEdit_5.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_5.setObjectName(_fromUtf8("lineEdit_5"))
        self.label_6 = QtGui.QLabel(self.groupBox_2)
        self.label_6.setGeometry(QtCore.QRect(280, 60, 46, 20))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.label_7 = QtGui.QLabel(self.groupBox_2)
        self.label_7.setGeometry(QtCore.QRect(80, 60, 46, 20))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.lineEdit_6 = QtGui.QLineEdit(self.groupBox_2)
        self.lineEdit_6.setEnabled(False)
        self.lineEdit_6.setGeometry(QtCore.QRect(320, 60, 41, 20))
        self.lineEdit_6.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_6.setObjectName(_fromUtf8("lineEdit_6"))
        self.label_10 = QtGui.QLabel(self.groupBox_2)
        self.label_10.setGeometry(QtCore.QRect(10, 90, 61, 16))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.lineEdit_9 = QtGui.QLineEdit(self.groupBox_2)
        self.lineEdit_9.setEnabled(False)
        self.lineEdit_9.setGeometry(QtCore.QRect(230, 140, 91, 20))
        self.lineEdit_9.setText(_fromUtf8(""))
        self.lineEdit_9.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_9.setObjectName(_fromUtf8("lineEdit_9"))
        self.label_9 = QtGui.QLabel(self.groupBox_2)
        self.label_9.setGeometry(QtCore.QRect(216, 144, 8, 13))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.lineEdit_10 = QtGui.QLineEdit(self.groupBox_2)
        self.lineEdit_10.setEnabled(False)
        self.lineEdit_10.setGeometry(QtCore.QRect(120, 140, 91, 20))
        self.lineEdit_10.setText(_fromUtf8(""))
        self.lineEdit_10.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_10.setObjectName(_fromUtf8("lineEdit_10"))
        self.pushButton_3 = QtGui.QPushButton(self.groupBox_2)
        self.pushButton_3.setEnabled(False)
        self.pushButton_3.setGeometry(QtCore.QRect(350, 140, 75, 20))
        self.pushButton_3.setObjectName(_fromUtf8("pushButton_3"))
        self.lineEdit_11 = QtGui.QLineEdit(self.groupBox_2)
        self.lineEdit_11.setEnabled(False)
        self.lineEdit_11.setGeometry(QtCore.QRect(150, 30, 91, 20))
        self.lineEdit_11.setInputMask(_fromUtf8(""))
        self.lineEdit_11.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_11.setPlaceholderText(_fromUtf8(""))
        self.lineEdit_11.setObjectName(_fromUtf8("lineEdit_11"))
        self.pushButton_7 = QtGui.QPushButton(self.groupBox_2)
        self.pushButton_7.setGeometry(QtCore.QRect(390, 169, 31, 20))
        self.pushButton_7.setObjectName(_fromUtf8("pushButton_7"))
        self.label_8 = QtGui.QLabel(self.groupBox_2)
        self.label_8.setGeometry(QtCore.QRect(70, 144, 46, 13))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.pushButton_5 = QtGui.QPushButton(self.groupBox_2)
        self.pushButton_5.setGeometry(QtCore.QRect(120, 170, 21, 23))
        self.pushButton_5.setObjectName(_fromUtf8("pushButton_5"))
        self.groupBox_5 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_5.setGeometry(QtCore.QRect(480, 330, 381, 114))
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.label_17 = QtGui.QLabel(self.groupBox_5)
        self.label_17.setGeometry(QtCore.QRect(10, 30, 46, 20))
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.spinBox_2 = QtGui.QSpinBox(self.groupBox_5)
        self.spinBox_2.setEnabled(False)
        self.spinBox_2.setGeometry(QtCore.QRect(50, 30, 51, 20))
        self.spinBox_2.setMinimum(1)
        self.spinBox_2.setMaximum(9000)
        self.spinBox_2.setObjectName(_fromUtf8("spinBox_2"))
        self.pushButton_6 = QtGui.QPushButton(self.groupBox_5)
        self.pushButton_6.setEnabled(False)
        self.pushButton_6.setGeometry(QtCore.QRect(120, 30, 75, 20))
        self.pushButton_6.setObjectName(_fromUtf8("pushButton_6"))
        self.pushButton_9 = QtGui.QPushButton(self.groupBox_5)
        self.pushButton_9.setEnabled(False)
        self.pushButton_9.setGeometry(QtCore.QRect(290, 80, 75, 23))
        self.pushButton_9.setObjectName(_fromUtf8("pushButton_9"))
        self.groupBox_3 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(480, 450, 151, 51))
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.comboBox_3 = QtGui.QComboBox(self.groupBox_3)
        self.comboBox_3.setEnabled(False)
        self.comboBox_3.setGeometry(QtCore.QRect(30, 20, 101, 20))
        self.comboBox_3.setObjectName(_fromUtf8("comboBox_3"))
        self.label_14 = QtGui.QLabel(self.groupBox_3)
        self.label_14.setEnabled(True)
        self.label_14.setGeometry(QtCore.QRect(16, 20, 9, 20))
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.groupBox_6 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_6.setGeometry(QtCore.QRect(480, 510, 321, 51))
        self.groupBox_6.setObjectName(_fromUtf8("groupBox_6"))
        self.spinBox = QtGui.QSpinBox(self.groupBox_6)
        self.spinBox.setEnabled(False)
        self.spinBox.setGeometry(QtCore.QRect(183, 20, 51, 20))
        self.spinBox.setMinimum(1)
        self.spinBox.setMaximum(1)
        self.spinBox.setObjectName(_fromUtf8("spinBox"))
        self.comboBox_2 = QtGui.QComboBox(self.groupBox_6)
        self.comboBox_2.setEnabled(False)
        self.comboBox_2.setGeometry(QtCore.QRect(35, 20, 101, 20))
        self.comboBox_2.setObjectName(_fromUtf8("comboBox_2"))
        self.label_12 = QtGui.QLabel(self.groupBox_6)
        self.label_12.setEnabled(True)
        self.label_12.setGeometry(QtCore.QRect(10, 20, 21, 20))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.label_13 = QtGui.QLabel(self.groupBox_6)
        self.label_13.setGeometry(QtCore.QRect(143, 20, 46, 20))
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.lineEdit_12 = QtGui.QLineEdit(self.groupBox_6)
        self.lineEdit_12.setGeometry(QtCore.QRect(240, 20, 71, 20))
        self.lineEdit_12.setMouseTracking(True)
        self.lineEdit_12.setAcceptDrops(True)
        self.lineEdit_12.setDragEnabled(False)
        self.lineEdit_12.setReadOnly(True)
        self.lineEdit_12.setObjectName(_fromUtf8("lineEdit_12"))
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.groupBox.setTitle(_translate("MainWindow", "Data Input", None))
        self.label.setText(_translate("MainWindow", "Data Info:", None))
        self.label_2.setText(_translate("MainWindow", "Processing:", None))
        self.label_11.setText(_translate("MainWindow", "Data Format:", None))
        self.comboBox.setItemText(0, _translate("MainWindow", "Amp/Phase", None))
        self.comboBox.setItemText(1, _translate("MainWindow", "Amp[dB]/Phase", None))
        self.comboBox.setItemText(2, _translate("MainWindow", "Real/Imag", None))
        self.pushButton_4.setText(_translate("MainWindow", "Clear", None))
        self.pushButton.setText(_translate("MainWindow", "Load Dir", None))
        self.pushButton_2.setText(_translate("MainWindow", "Load Data", None))
        self.label_18.setText(_translate("MainWindow", "Columns:", None))
        self.comboBox_4.setItemText(0, _translate("MainWindow", "1", "5"))
        self.comboBox_4.setItemText(1, _translate("MainWindow", "2", None))
        self.comboBox_4.setItemText(2, _translate("MainWindow", "3", None))
        self.comboBox_4.setItemText(3, _translate("MainWindow", "4", None))
        self.comboBox_4.setItemText(4, _translate("MainWindow", "5", None))
        self.comboBox_4.setItemText(5, _translate("MainWindow", "6", None))
        self.comboBox_4.setItemText(6, _translate("MainWindow", "7", None))
        self.comboBox_4.setItemText(7, _translate("MainWindow", "8", None))
        self.comboBox_4.setItemText(8, _translate("MainWindow", "9", None))
        self.comboBox_4.setItemText(9, _translate("MainWindow", "10", None))
        self.comboBox_4.setItemText(10, _translate("MainWindow", "11", None))
        self.comboBox_4.setItemText(11, _translate("MainWindow", "12", None))
        self.comboBox_5.setItemText(0, _translate("MainWindow", "1", None))
        self.comboBox_5.setItemText(1, _translate("MainWindow", "2", None))
        self.comboBox_5.setItemText(2, _translate("MainWindow", "3", None))
        self.comboBox_5.setItemText(3, _translate("MainWindow", "4", None))
        self.comboBox_5.setItemText(4, _translate("MainWindow", "5", None))
        self.comboBox_5.setItemText(5, _translate("MainWindow", "6", None))
        self.comboBox_5.setItemText(6, _translate("MainWindow", "7", None))
        self.comboBox_5.setItemText(7, _translate("MainWindow", "8", None))
        self.comboBox_5.setItemText(8, _translate("MainWindow", "9", None))
        self.comboBox_5.setItemText(9, _translate("MainWindow", "10", None))
        self.comboBox_5.setItemText(10, _translate("MainWindow", "11", None))
        self.comboBox_5.setItemText(11, _translate("MainWindow", "12", None))
        self.radioButton.setText(_translate("MainWindow", "Notch-Res.", None))
        self.radioButton_2.setText(_translate("MainWindow", "Lorentz", None))
        self.label_4.setText(_translate("MainWindow", "x_val:", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.widget), _translate("MainWindow", "3D-Plots", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "2D-Plots", None))
        self.groupBox_2.setTitle(_translate("MainWindow", "Plot Settings", None))
        self.label_3.setText(_translate("MainWindow", "x (scan_var):", None))
        self.label_5.setText(_translate("MainWindow", "unit:", None))
        self.lineEdit_4.setText(_translate("MainWindow", "-", None))
        self.lineEdit_5.setText(_translate("MainWindow", "Frequency", None))
        self.label_6.setText(_translate("MainWindow", "unit:", None))
        self.label_7.setText(_translate("MainWindow", "y:", None))
        self.lineEdit_6.setText(_translate("MainWindow", "GHz", None))
        self.label_10.setText(_translate("MainWindow", "Cut Data:", None))
        self.label_9.setText(_translate("MainWindow", "--", None))
        self.pushButton_3.setText(_translate("MainWindow", "Cut", None))
        self.lineEdit_11.setText(_translate("MainWindow", "x", None))
        self.pushButton_7.setText(_translate("MainWindow", "?", None))
        self.label_8.setText(_translate("MainWindow", "y_range:", None))
        self.pushButton_5.setText(_translate("MainWindow", "<-", None))
        self.groupBox_5.setTitle(_translate("MainWindow", "Fit Parameters", None))
        self.label_17.setText(_translate("MainWindow", "Scan:", None))
        self.pushButton_6.setText(_translate("MainWindow", "Save", None))
        self.pushButton_9.setText(_translate("MainWindow", "Save All", None))
        self.groupBox_3.setTitle(_translate("MainWindow", "3-D Plot", None))
        self.label_14.setText(_translate("MainWindow", "z:", None))
        self.groupBox_6.setTitle(_translate("MainWindow", "2-D Plot", None))
        self.label_12.setText(_translate("MainWindow", "z(y):", None))
        self.label_13.setText(_translate("MainWindow", "Scan:", None))

from matplotlibwidget import MatplotlibWidget
