name: Tests

on:
  push:
    branches: 'master'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - name: Retrieve Tags
        run: git fetch origin 'refs/tags/*:refs/tags/*'
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.x'
      - name: Install build dependencies
        run: python -m pip install -U hatch hatch-vcs
      - name: Run tests
        run: hatch test --cover-quiet --randomize